import type { NextPage } from "next";
import Head from "next/head";
import { Data } from "../types/Data";
import useSwr from "swr";
import Card from "../components/Card";
import {
  Heading,
  HStack,
  SimpleGrid,
  VStack,
  Tabs,
  TabList,
  Tab,
} from "@chakra-ui/react";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { fetchRoute } from "../services/fetchData";

const calculateRealIndex = (page: number, index: number) => {
  return page * 20 + index;
};

const Home: NextPage = () => {
  const router = useRouter();
  const [page, setPage] = useState<number>(0);
  const { data } = useSwr<Data[]>(`/api?page=${page}`, fetchRoute);

  useEffect(() => {
    const { page } = router.query;
    if (!isNaN(Number(page))) {
      setPage(Number(page));
    }
  }, [router.query]);

  return (
    <VStack>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack w="100%">
        {/* Top Row */}
        <HStack
          justify={{ base: "start", lg: "center" }}
          py={8}
          w="100%"
          bg=""
          position="relative"
        >
          <Heading fontWeight="thin" mx={{ base: "4", lg: "auto" }}>
            Select a Plant
          </Heading>
          <HStack position="absolute" right={{ base: 5, lg: 20 }}>
            <Tabs onChange={(index) => setPage(index)} index={page}>
              <TabList>
                <Tab>1</Tab>
                <Tab>2</Tab>
                <Tab>3</Tab>
                <Tab>4</Tab>
              </TabList>
            </Tabs>
          </HStack>
        </HStack>

        {/* Grid */}
        <SimpleGrid
          columns={{ base: 1, lg: 3 }}
          spacing={6}
          bg=""
          p={8}
          maxW={{ base: "100%", md: "80%" }}
        >
          {data?.map((d, i) => (
            <Card data={d} key={d.name} index={calculateRealIndex(page, i)} />
          ))}
        </SimpleGrid>
      </VStack>
    </VStack>
  );
};

export default Home;
