import type { NextPage } from "next";
import Head from "next/head";
import { Data } from "../types/data";
import axios from "axios";
import useSwr from "swr";
import Card from "../components/Card";
import { Text, Heading, HStack, SimpleGrid, VStack, Tabs, TabList, Tab } from "@chakra-ui/react";
import { useState } from "react";

const fetchData = async (route: string) => {
  const { data } = await axios.get(route);
  return data;
};

const Home: NextPage = () => {
  const [page, setPage] = useState<number>(0);
  const { data } = useSwr<Data[]>(`/api?page=${page}`, fetchData);

  return (
    <VStack >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack w="100%">
        {/* Top Row */}
        <HStack justify="center" py={8} w="100%" bg="" position="relative">
          <Heading mx="auto" fontWeight="thin">
            Select a Plant
          </Heading>
          <HStack position="absolute" right={20}>
            <Tabs onChange={(index) => setPage(index)}>
              <TabList>
                <Tab>1</Tab>
                <Tab>2</Tab>
                <Tab>3</Tab>
                <Tab>4</Tab>
              </TabList>
            </Tabs>
          </HStack>
        </HStack>

        {/* Grid */}
        <SimpleGrid columns={{ base: 1, lg: 3 }} spacing={6} bg="" p={8} maxW="80%">
          {data?.map((d) => (
            <Card data={d} />
          ))}
        </SimpleGrid>
      </VStack>
    </VStack>
  );
};

export default Home;
